sudo: required
dist: trusty
services: docker
before_install:
- openssl aes-256-cbc -K $encrypted_65b80f527c7e_key -iv $encrypted_65b80f527c7e_iv -in .dropbox_uploader.enc -out ~/.dropbox_uploader -d
script:
- mkdir -pv _build/{appendices,chapters}
- ./latexdockercmd.sh latexmk -pdf -f -quiet -outdir=./_build main.tex
- ./dropbox_uploader.sh upload _build/main.pdf ${TRAVIS_BRANCH}/main-latest.pdf
- ./dropbox_uploader.sh upload _build/main.pdf ${TRAVIS_BRANCH}/main-${TRAVIS_JOB_NUMBER}.pdf
